-- Create media_assets table to index storage objects
create table if not exists public.media_assets (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null,
  bucket text not null,
  path text,
  meta jsonb,
  created_at timestamptz not null default now()
);

alter table public.media_assets enable row level security;
drop policy if exists "Media assets read" on public.media_assets;
create policy "Media assets read" on public.media_assets for select using (true);
drop policy if exists "Media assets write" on public.media_assets;
create policy "Media assets write" on public.media_assets for all using (true) with check (true);

-- Create hero_media_settings table
create table if not exists public.hero_media_settings (
  id bigint generated by default as identity primary key,
  page_name text not null,
  media_type text not null default 'image',
  media_url text,
  desktop_height integer,
  tablet_height integer,
  mobile_height integer,
  overlay_enabled boolean not null default true,
  overlay_opacity numeric default 0.5,
  object_fit text default 'cover',
  video_autoplay boolean not null default false,
  video_loop boolean not null default false,
  video_muted boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.hero_media_settings enable row level security;
drop policy if exists "Hero media read" on public.hero_media_settings;
create policy "Hero media read" on public.hero_media_settings for select using (true);
drop policy if exists "Hero media write" on public.hero_media_settings;
create policy "Hero media write" on public.hero_media_settings for all using (true) with check (true);
