-- Create hero_marquee_announcements table
create table if not exists public.hero_marquee_announcements (
  id bigint generated by default as identity primary key,
  title text not null default '',
  text text not null default '',
  image_url text not null default '',
  image_width integer,
  image_height integer,
  image_gap integer,
  scroll_speed integer not null default 25,
  pause_on_hover boolean not null default true,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.hero_marquee_announcements enable row level security;
drop policy if exists "Hero marquee read" on public.hero_marquee_announcements;
create policy "Hero marquee read" on public.hero_marquee_announcements for select using (true);
drop policy if exists "Hero marquee write" on public.hero_marquee_announcements;
create policy "Hero marquee write" on public.hero_marquee_announcements for all using (true) with check (true);

-- Create enquiry popup settings table
create table if not exists public.enquiry_popup_settings (
  id bigint generated by default as identity primary key,
  enabled boolean not null default false,
  title text not null default '',
  description text not null default '',
  show_name boolean not null default true,
  show_email boolean not null default true,
  show_phone boolean not null default true,
  show_message boolean not null default true,
  button_text text not null default 'Submit',
  success_message text not null default 'Thank you',
  popup_image text not null default '',
  display_delay integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.enquiry_popup_settings enable row level security;
drop policy if exists "Enquiry settings read" on public.enquiry_popup_settings;
create policy "Enquiry settings read" on public.enquiry_popup_settings for select using (true);
drop policy if exists "Enquiry settings write" on public.enquiry_popup_settings;
create policy "Enquiry settings write" on public.enquiry_popup_settings for all using (true) with check (true);

-- Create enquiries table
create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  phone text,
  message text,
  created_at timestamptz not null default now()
);

alter table public.enquiries enable row level security;
drop policy if exists "Enquiries insert" on public.enquiries;
create policy "Enquiries insert" on public.enquiries for insert using (true) with check (true);
drop policy if exists "Enquiries read" on public.enquiries;
create policy "Enquiries read" on public.enquiries for select using (true);
