create table if not exists public.announcement_images (
  id bigint generated by default as identity primary key,
  announcement_id text not null,
  image_url text not null,
  width integer,
  height integer,
  gap integer,
  border_radius integer,
  object_fit text not null default 'cover',
  created_at timestamptz not null default now()
);

create index if not exists announcement_images_announcement_id_idx
  on public.announcement_images (announcement_id);

alter table public.announcement_images enable row level security;
drop policy if exists "Announcement images read" on public.announcement_images;
create policy "Announcement images read" on public.announcement_images for select using (true);
drop policy if exists "Announcement images write" on public.announcement_images;
create policy "Announcement images write" on public.announcement_images for all using (true) with check (true);

create table if not exists public.enquiry_settings (
  id bigint generated by default as identity primary key,
  enabled boolean not null default false,
  title text not null default '',
  description text not null default '',
  show_name boolean not null default true,
  show_email boolean not null default true,
  show_phone boolean not null default true,
  show_message boolean not null default true,
  button_text text not null default 'Submit',
  success_message text not null default 'Thank you. We will contact you soon.',
  popup_image text not null default '',
  display_delay integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.enquiry_settings enable row level security;
drop policy if exists "Enquiry settings public read" on public.enquiry_settings;
create policy "Enquiry settings public read" on public.enquiry_settings for select using (true);
drop policy if exists "Enquiry settings write" on public.enquiry_settings;
create policy "Enquiry settings write" on public.enquiry_settings for all using (true) with check (true);

alter table if exists public.enquiries add column if not exists description text;
alter table if exists public.announcement_top add column if not exists title text default '';
alter table if exists public.announcement_hero add column if not exists title text default '';
