create table if not exists public.page_sections (
  id bigint generated by default as identity primary key,
  page_name text not null,
  section_name text not null,
  title text not null default '',
  content jsonb not null default '{}'::jsonb,
  image_url text not null default '',
  previous_data jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists page_sections_page_section_key_idx
  on public.page_sections (page_name, section_name);

alter table public.page_sections enable row level security;

drop policy if exists "Page sections read" on public.page_sections;
create policy "Page sections read" on public.page_sections
  for select
  using (true);

drop policy if exists "Page sections write" on public.page_sections;
create policy "Page sections write" on public.page_sections
  for all
  using (true)
  with check (true);

create table if not exists public.popup_poster (
  id bigint generated by default as identity primary key,
  enabled boolean not null default true,
  title text not null default '',
  description text not null default '',
  cta_text text not null default '',
  cta_url text not null default '',
  media_url text not null default '',
  media_type text not null default 'image',
  display_delay integer not null default 0,
  previous_data jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists popup_poster_created_at_idx
  on public.popup_poster (created_at desc);

alter table public.popup_poster enable row level security;

drop policy if exists "Popup poster read" on public.popup_poster;
create policy "Popup poster read" on public.popup_poster
  for select
  using (true);

drop policy if exists "Popup poster write" on public.popup_poster;
create policy "Popup poster write" on public.popup_poster
  for all
  using (true)
  with check (true);
