-- Create plural popup_posters table with extra image size fields
create table if not exists public.popup_posters (
  id bigint generated by default as identity primary key,
  title text not null default '',
  description text not null default '',
  cta_text text not null default '',
  cta_url text not null default '',
  media_url text not null default '',
  media_type text not null default 'image',
  image_width integer,
  image_height integer,
  enabled boolean not null default true,
  display_delay integer not null default 0,
  previous_data jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists popup_posters_created_at_idx
  on public.popup_posters (created_at desc);

alter table public.popup_posters enable row level security;

drop policy if exists "Popup posters read" on public.popup_posters;
create policy "Popup posters read" on public.popup_posters
  for select
  using (true);

drop policy if exists "Popup posters write" on public.popup_posters;
create policy "Popup posters write" on public.popup_posters
  for all
  using (true)
  with check (true);

-- Announcement bars
create table if not exists public.announcement_top (
  id bigint generated by default as identity primary key,
  text text not null default '',
  image_url text not null default '',
  speed integer not null default 25,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.announcement_top enable row level security;
drop policy if exists "Announcement top read" on public.announcement_top;
create policy "Announcement top read" on public.announcement_top for select using (true);
drop policy if exists "Announcement top write" on public.announcement_top;
create policy "Announcement top write" on public.announcement_top for all using (true) with check (true);

create table if not exists public.announcement_hero (
  id bigint generated by default as identity primary key,
  text text not null default '',
  image_url text not null default '',
  speed integer not null default 25,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.announcement_hero enable row level security;
drop policy if exists "Announcement hero read" on public.announcement_hero;
create policy "Announcement hero read" on public.announcement_hero for select using (true);
drop policy if exists "Announcement hero write" on public.announcement_hero;
create policy "Announcement hero write" on public.announcement_hero for all using (true) with check (true);
